import assert from 'node:assert/strict'
import { copyFile, mkdtemp, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { after, before, test } from 'node:test'
import { fileURLToPath } from 'node:url'
import type { Transcript } from '../shared/meetings.ts'

/**
 * Two genuinely different voices reading in turn, generated by `npm run fixtures`.
 * The point of the feature is telling them apart across meetings, so a fixture with
 * one voice would prove nothing.
 */
const FIXTURE = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'spike', 'fixtures', 'two-speakers.wav')

let dir: string
let transcript: Transcript
let available = true
let voices: typeof import('./voices.ts')

// The turns the fixture was built from: A speaks, then B, then A, then B.
const SEGMENTS = [
  { t0: 0.0, t1: 6.6, speaker: 'SPEAKER_00', text: 'a1' },
  { t0: 7.2, t1: 11.9, speaker: 'SPEAKER_01', text: 'b1' },
  { t0: 12.5, t1: 17.9, speaker: 'SPEAKER_00', text: 'a2' },
  { t0: 18.4, t1: 22.8, speaker: 'SPEAKER_01', text: 'b2' },
]

before(async () => {
  dir = await mkdtemp(join(tmpdir(), 'voices-test-'))
  process.env['VOICES_FILE'] = join(dir, 'voices.json')
  voices = await import('./voices.ts')

  transcript = {
    id: 'fixture',
    startedAt: '2026-08-27T14:00:00+07:00',
    durationSec: 23,
    speakers: { SPEAKER_00: 'Speaker 1', SPEAKER_01: 'Speaker 2' },
    segments: SEGMENTS,
  }
  await writeFile(join(dir, 'transcript.json'), JSON.stringify(transcript))
  await copyFile(FIXTURE, join(dir, 'loopback.wav')).catch(() => {
    available = false
  })
})

after(() => {
  delete process.env['VOICES_FILE']
})

const skip = () => !available

test('voices: a named voice is recognised again, and a different one is not', { skip: skip() }, async () => {
  assert.deepEqual(await voices.knownVoices(), [], 'starts with nothing learned')

  await voices.remember(dir, transcript, 'SPEAKER_00', 'พี่โจ้')
  assert.deepEqual(await voices.knownVoices(), ['พี่โจ้'])

  // The same voice in the same recording must come back with the name on it.
  assert.equal((await voices.identify(dir, transcript, 'SPEAKER_00'))?.name, 'พี่โจ้')

  // The other speaker must not. A wrong name attached to someone else's words is
  // worse than an unnamed speaker.
  assert.equal(await voices.identify(dir, transcript, 'SPEAKER_01'), null)
})

test('voices: forgetting a voice stops it matching', { skip: skip() }, async () => {
  await voices.remember(dir, transcript, 'SPEAKER_01', 'น้องมิ้น')
  assert.equal((await voices.identify(dir, transcript, 'SPEAKER_01'))?.name, 'น้องมิ้น')

  await voices.forget('น้องมิ้น')
  assert.equal(await voices.identify(dir, transcript, 'SPEAKER_01'), null)
  assert.ok(!(await voices.knownVoices()).includes('น้องมิ้น'))
})

test('voices: a voice keeps the same id across remember() calls for the same name', { skip: skip() }, async () => {
  await voices.remember(dir, transcript, 'SPEAKER_00', 'คุณเอ');
  const first = await voices.identify(dir, transcript, 'SPEAKER_00')
  assert.ok(first?.id, 'expected an id on a freshly remembered voice')

  // Re-remembered under the same name (e.g. a refreshed embedding from a later
  // meeting) — the id must survive, since a future rename-propagation feature (not
  // built here) will need it to stay stable across exactly this.
  await voices.remember(dir, transcript, 'SPEAKER_00', 'คุณเอ')
  const second = await voices.identify(dir, transcript, 'SPEAKER_00')
  assert.equal(second?.id, first?.id)
})

test('voices: a legacy entry with no id gets a stable, deterministic one on every read', { skip: skip() }, async () => {
  await voices.remember(dir, transcript, 'SPEAKER_00', 'ลุงตี๋')
  const file = process.env['VOICES_FILE']!
  const raw = JSON.parse(await readFile(file, 'utf8')) as { id: string; name: string; embedding: number[] }[]
  // Strip the id, as if this entry was written before the field existed.
  await writeFile(file, JSON.stringify(raw.map(({ id: _id, ...rest }) => rest)))

  const a = await voices.identify(dir, transcript, 'SPEAKER_00')
  const b = await voices.identify(dir, transcript, 'SPEAKER_00')
  assert.ok(a?.id, 'expected a backfilled id')
  assert.equal(a?.id, b?.id, 'the same legacy voice must resolve to the same id on every read, not a fresh random one')
})

test('voices: a speaker with almost no audio is not learned', { skip: skip() }, async () => {
  // An embedding from a fragment is mostly noise, and a bad one poisons every later
  // match, so too little audio must produce nothing rather than something wrong.
  const brief: Transcript = { ...transcript, segments: [{ t0: 0, t1: 0.4, speaker: 'SPEAKER_00', text: 'x' }] }
  await voices.remember(dir, brief, 'SPEAKER_00', 'ไม่ควรจำ')
  assert.ok(!(await voices.knownVoices()).includes('ไม่ควรจำ'))
})
