import assert from 'node:assert/strict'
import { copyFile, mkdtemp, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { after, before, test } from 'node:test'
import { fileURLToPath } from 'node:url'
import type { Transcript } from '../shared/meetings.ts'

/**
 * Two genuinely different voices reading in turn, generated by `npm run fixtures`.
 * The point of the feature is telling them apart across meetings, so a fixture with
 * one voice would prove nothing.
 */
const FIXTURE = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'spike', 'fixtures', 'two-speakers.wav')

let dir: string
let transcript: Transcript
let available = true
let voices: typeof import('./voices.ts')

// The turns the fixture was built from: A speaks, then B, then A, then B.
const SEGMENTS = [
  { t0: 0.0, t1: 6.6, speaker: 'SPEAKER_00', text: 'a1' },
  { t0: 7.2, t1: 11.9, speaker: 'SPEAKER_01', text: 'b1' },
  { t0: 12.5, t1: 17.9, speaker: 'SPEAKER_00', text: 'a2' },
  { t0: 18.4, t1: 22.8, speaker: 'SPEAKER_01', text: 'b2' },
]

before(async () => {
  dir = await mkdtemp(join(tmpdir(), 'voices-test-'))
  process.env['VOICES_FILE'] = join(dir, 'voices.json')
  voices = await import('./voices.ts')

  transcript = {
    id: 'fixture',
    startedAt: '2026-08-27T14:00:00+07:00',
    durationSec: 23,
    speakers: { SPEAKER_00: 'Speaker 1', SPEAKER_01: 'Speaker 2' },
    segments: SEGMENTS,
  }
  await writeFile(join(dir, 'transcript.json'), JSON.stringify(transcript))
  await copyFile(FIXTURE, join(dir, 'loopback.wav')).catch(() => {
    available = false
  })
})

after(() => {
  delete process.env['VOICES_FILE']
})

const skip = () => !available

test('voices: a named voice is recognised again, and a different one is not', { skip: skip() }, async () => {
  assert.deepEqual(await voices.knownVoices(), [], 'starts with nothing learned')

  await voices.remember(dir, transcript, 'SPEAKER_00', 'พี่โจ้')
  assert.deepEqual(await voices.knownVoices(), ['พี่โจ้'])

  // The same voice in the same recording must come back with the name on it.
  assert.equal((await voices.identify(dir, transcript, 'SPEAKER_00'))?.name, 'พี่โจ้')

  // The other speaker must not. A wrong name attached to someone else's words is
  // worse than an unnamed speaker.
  assert.equal(await voices.identify(dir, transcript, 'SPEAKER_01'), null)
})

test('voices: forgetting a voice stops it matching', { skip: skip() }, async () => {
  await voices.remember(dir, transcript, 'SPEAKER_01', 'น้องมิ้น')
  assert.equal((await voices.identify(dir, transcript, 'SPEAKER_01'))?.name, 'น้องมิ้น')

  await voices.forget('น้องมิ้น')
  assert.equal(await voices.identify(dir, transcript, 'SPEAKER_01'), null)
  assert.ok(!(await voices.knownVoices()).includes('น้องมิ้น'))
})

test('voices: a voice keeps the same id across remember() calls for the same name', { skip: skip() }, async () => {
  await voices.remember(dir, transcript, 'SPEAKER_00', 'คุณเอ');
  const first = await voices.identify(dir, transcript, 'SPEAKER_00')
  assert.ok(first?.id, 'expected an id on a freshly remembered voice')

  // Re-remembered under the same name (e.g. a refreshed embedding from a later
  // meeting) — the id must survive, since a future rename-propagation feature (not
  // built here) will need it to stay stable across exactly this.
  await voices.remember(dir, transcript, 'SPEAKER_00', 'คุณเอ')
  const second = await voices.identify(dir, transcript, 'SPEAKER_00')
  assert.equal(second?.id, first?.id)
})

test('voices: a legacy entry with no id gets a stable, deterministic one on every read', { skip: skip() }, async () => {
  await voices.remember(dir, transcript, 'SPEAKER_00', 'ลุงตี๋')
  const file = process.env['VOICES_FILE']!
  const raw = JSON.parse(await readFile(file, 'utf8')) as { id: string; name: string; embedding: number[] }[]
  // Strip the id, as if this entry was written before the field existed.
  await writeFile(file, JSON.stringify(raw.map(({ id: _id, ...rest }) => rest)))

  const a = await voices.identify(dir, transcript, 'SPEAKER_00')
  const b = await voices.identify(dir, transcript, 'SPEAKER_00')
  assert.ok(a?.id, 'expected a backfilled id')
  assert.equal(a?.id, b?.id, 'the same legacy voice must resolve to the same id on every read, not a fresh random one')
})

test('voices: a speaker with almost no audio is not learned', { skip: skip() }, async () => {
  // An embedding from a fragment is mostly noise, and a bad one poisons every later
  // match, so too little audio must produce nothing rather than something wrong.
  const brief: Transcript = { ...transcript, segments: [{ t0: 0, t1: 0.4, speaker: 'SPEAKER_00', text: 'x' }] }
  await voices.remember(dir, brief, 'SPEAKER_00', 'ไม่ควรจำ')
  assert.ok(!(await voices.knownVoices()).includes('ไม่ควรจำ'))
})

test(
  'voices: the same unnamed voice heard twice stays one pending entry; a genuinely different one gets its own',
  { skip: skip() },
  async () => {
    // "Heard in meeting X" then "heard again in meeting Y" — trackPending only cares
    // about the embedding, not the meeting id, so reusing the same fixture dir/speaker
    // under two different meeting ids is exactly the cross-meeting case (spec item 1).
    const firstId = await voices.trackPending(dir, transcript, 'SPEAKER_00', 'meeting-a')
    assert.ok(firstId, 'expected a pending id for a genuinely unnamed voice')
    const secondId = await voices.trackPending(dir, transcript, 'SPEAKER_00', 'meeting-b')
    assert.equal(secondId, firstId, 'the same voice heard again must not create a second pending entry')

    // A different real person's voice must NOT collapse into the same pending entry.
    const otherId = await voices.trackPending(dir, transcript, 'SPEAKER_01', 'meeting-a')
    assert.ok(otherId, 'expected a pending id for the second voice')
    assert.notEqual(otherId, firstId, 'two different voices must stay two pending entries')

    const pending = await voices.pendingVoices()
    assert.ok(pending.some((p) => p.id === firstId))
    assert.ok(pending.some((p) => p.id === otherId))
    // firstHeard is fixed at creation — re-tracking the same voice must not have
    // overwritten it with the second sighting's meeting id.
    assert.equal(pending.find((p) => p.id === firstId)?.meetingId, 'meeting-a')
  },
)

test('voices: naming a pending voice clears it from the pending list everywhere it was heard', { skip: skip() }, async () => {
  const id = await voices.trackPending(dir, transcript, 'SPEAKER_00', 'meeting-c')
  assert.ok(id)
  assert.ok((await voices.pendingVoices()).some((p) => p.id === id))

  await voices.nameVoice(id!, 'พี่หนึ่ง')
  assert.ok(!(await voices.pendingVoices()).some((p) => p.id === id), 'must stop being pending once named')
  assert.ok((await voices.knownVoices()).includes('พี่หนึ่ง'))
  // (Whether identify() now picks this exact id for SPEAKER_00 over an older named
  // voice built from the same fixture audio is a tie-breaking question this test
  // doesn't need to answer — the pending/known-list checks above are the behaviour
  // spec item 1 actually asks for.)
})

test('voices: renaming a speaker the app already recognised retargets that id, not a fresh one', { skip: skip() }, async () => {
  const first = await voices.remember(dir, transcript, 'SPEAKER_01', 'คุณบี')
  assert.ok(first)

  // Simulates what diarizeMeeting/meeting:rename thread through: this speaker key was
  // already tied to `first` by a previous pass (Transcript.speakerVoices).
  const recognised: Transcript = {
    ...transcript,
    speakerVoices: { SPEAKER_01: { voiceId: first!, name: 'คุณบี' } },
  }
  const second = await voices.remember(dir, recognised, 'SPEAKER_01', 'คุณบีทู')
  assert.equal(second, first, 'a recognised speaker must be renamed in place, by id — not given a new one')
  assert.ok((await voices.knownVoices()).includes('คุณบีทู'))
  assert.ok(!(await voices.knownVoices()).includes('คุณบี'), 'the old name must not linger as a second entry')
})

test('voices: resolveSpeakerNames resolves the live name, then the stored fallback, then leaves an unrecognised key alone', async () => {
  const id = (await voices.remember(dir, transcript, 'SPEAKER_00', 'พี่ซี'))!

  // A key speakerVoices never covered (e.g. 'me', or a transcript older than this
  // feature) must pass through untouched.
  const untouched = await voices.resolveSpeakerNames({ me: 'You', SPEAKER_00: 'Speaker 1' })
  assert.deepEqual(untouched, { me: 'You', SPEAKER_00: 'Speaker 1' })

  // The live name wins over whatever was stored on the transcript at diarize time.
  const live = await voices.resolveSpeakerNames(
    { SPEAKER_00: 'Speaker 1' },
    { SPEAKER_00: { voiceId: id, name: 'Speaker 1' } },
  )
  assert.equal(live['SPEAKER_00'], 'พี่ซี')

  // Once the voice is forgotten, fall back to the name recorded on the transcript at
  // diarize time — never undefined, never the raw key.
  await voices.forget('พี่ซี')
  const forgotten = await voices.resolveSpeakerNames(
    { SPEAKER_00: 'Speaker 1' },
    { SPEAKER_00: { voiceId: id, name: 'Speaker 1 (พี่ซี)' } },
  )
  assert.equal(forgotten['SPEAKER_00'], 'Speaker 1 (พี่ซี)')
})

test('voices: resolveSpeakerNames never resolves a still-pending voice to a name (HIGH 3)', { skip: skip() }, async () => {
  const pendingId = await voices.trackPending(dir, transcript, 'SPEAKER_00', 'some-meeting')
  assert.ok(pendingId)

  // Simulates the exact HIGH 3 mechanism end to end: `rec.name` is contaminated with
  // "Alice", a name typed for a different physical person under the same reused raw
  // key on an earlier pass — but the live voice this id actually points at is still
  // pending (name: null). It must never win, even as a fallback: the pending voice
  // has no name to fall back to at all.
  const resolved = await voices.resolveSpeakerNames(
    { SPEAKER_00: 'Speaker 1' },
    { SPEAKER_00: { voiceId: pendingId!, name: 'Alice' } },
  )
  assert.equal(resolved['SPEAKER_00'], 'Speaker 1', 'must not fall back to a name that belongs to someone else entirely')
  assert.notEqual(resolved['SPEAKER_00'], 'Alice')
})

test('voices: pcmFor honours an explicit `spans` override over the transcript\'s own speaker filter (MEDIUM 6)', { skip: skip() }, async () => {
  // SPEAKER_01's real segments are t0=7.2..11.9 and t0=18.4..22.8 (SEGMENTS above) —
  // pointing `spans` at SPEAKER_00's own timing instead must pull SPEAKER_00's audio,
  // proving the override — not the current `speaker` key — decides what gets read.
  const bySpans = await voices.sampleWav(dir, transcript, 'SPEAKER_01', [{ t0: 0.0, t1: 6.6 }])
  const bySpeaker = await voices.sampleWav(dir, transcript, 'SPEAKER_00')
  assert.ok(bySpans && bySpeaker)
  // Compared as Buffers, not deepEqual: these are ~160KB of PCM, and assert's diff
  // for a mismatch inspects every byte — enough string building to get the test
  // process OOM-killed instead of reporting a failure.
  assert.ok(Buffer.from(bySpans).equals(Buffer.from(bySpeaker)), 'an explicit span must win over the speaker-key-derived one')
})
